name: Deploy Website to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04.3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: page

      - name: Build
        run: npm run build
        working-directory: page

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BUCKET_REGION }}

      - name: Sync dist to S3
        run: aws s3 sync page/dist s3://${{ secrets.BUCKET_NAME_WP }} --delete